# Generated by Django 3.0.1 on 2019-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toei',
            name='draw_flg',
            field=models.CharField(default=0, max_length=1, verbose_name='抽選フラグ'),
        ),
    ]
