# Generated by Django 3.0.1 on 2019-12-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0002_toei_draw_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=8, verbose_name='都営カードID')),
                ('year', models.CharField(max_length=4, verbose_name='年')),
                ('month', models.CharField(max_length=2, verbose_name='月')),
                ('day', models.CharField(max_length=2, verbose_name='日付')),
                ('from_time', models.CharField(max_length=2, verbose_name='開始時間')),
                ('to_time', models.CharField(max_length=2, verbose_name='終了時間')),
                ('court', models.CharField(max_length=1, verbose_name='コート')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('delete_flg', models.CharField(default=0, max_length=1, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name_plural': 'Draw',
            },
        ),
    ]
