# Generated by Django 3.0.1 on 2019-12-31 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toei', '0003_draw'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toei',
            unique_together={('card_id', 'user')},
        ),
    ]
