# Generated by Django 3.0.1 on 2019-12-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0004_auto_20191231_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='draw_conf_flg',
            field=models.CharField(default=0, max_length=1, verbose_name='抽選確認フラグ'),
        ),
    ]
