# Generated by Django 3.0.1 on 2019-12-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0005_draw_draw_conf_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toei',
            name='card_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='都営カードID'),
        ),
        migrations.AlterUniqueTogether(
            name='toei',
            unique_together=set(),
        ),
    ]
