# Generated by Django 3.0.1 on 2019-12-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0006_auto_20191231_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toei',
            name='id',
        ),
        migrations.AlterField(
            model_name='draw',
            name='draw_conf_flg',
            field=models.CharField(default=0, max_length=1, verbose_name='抽選確定フラグ'),
        ),
        migrations.AlterField(
            model_name='toei',
            name='card_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='都営カードID'),
        ),
    ]
