# Generated by Django 3.0.1 on 2019-12-31 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0007_auto_20200101_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toei.Toei', verbose_name='都営カードID'),
        ),
    ]
