# Generated by Django 3.0.1 on 2020-01-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0008_auto_20200101_0858'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='draw',
            table='draw',
        ),
        migrations.AlterModelTable(
            name='toei',
            table='toei',
        ),
    ]
