# Generated by Django 3.0.1 on 2020-01-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0010_auto_20200101_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draw',
            old_name='card',
            new_name='card_id',
        ),
    ]
