# Generated by Django 3.0.1 on 2020-01-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0011_auto_20200101_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draw',
            old_name='card_id',
            new_name='card',
        ),
    ]
