# Generated by Django 3.0.1 on 2020-01-01 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0012_auto_20200101_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draw',
            old_name='card',
            new_name='card_id',
        ),
        migrations.AlterField(
            model_name='draw',
            name='card_id',
            field=models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.PROTECT, to='toei.Toei', verbose_name='都営カードID'),
        ),
    ]
