# Generated by Django 3.0.1 on 2020-01-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0016_oddscourt'),
    ]

    operations = [
        migrations.AddField(
            model_name='oddscourt',
            name='apply_court',
            field=models.IntegerField(default=0, verbose_name='申込件数数'),
        ),
        migrations.AddField(
            model_name='oddscourt',
            name='empty_court',
            field=models.IntegerField(default=0, verbose_name='当選可能数'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='court',
            field=models.CharField(choices=[('0', '府中の森'), ('1', '小金井公園'), ('2', '野川公園'), ('3', '井の頭公園'), ('4', '武蔵野中央公園')], default=1, max_length=1, verbose_name='コート'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='court',
            field=models.CharField(choices=[('0', '府中の森'), ('1', '小金井公園'), ('2', '野川公園'), ('3', '井の頭公園'), ('4', '武蔵野中央公園')], default=1, max_length=1, verbose_name='コート'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='court',
            field=models.CharField(choices=[('0', '府中の森'), ('1', '小金井公園'), ('2', '野川公園'), ('3', '井の頭公園'), ('4', '武蔵野中央公園')], default=1, max_length=1, verbose_name='コート'),
        ),
        migrations.AlterField(
            model_name='toei',
            name='available_flg',
            field=models.CharField(choices=[('0', '無効'), ('1', '有効')], default=1, max_length=1, verbose_name='有効フラグ'),
        ),
    ]
