# Generated by Django 3.0.1 on 2020-01-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0017_auto_20200104_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddscourt',
            name='day',
            field=models.IntegerField(max_length=2, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='month',
            field=models.IntegerField(max_length=2, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='year',
            field=models.IntegerField(max_length=4, verbose_name='年'),
        ),
    ]
