# Generated by Django 3.0.1 on 2020-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0019_auto_20200104_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='day',
            field=models.IntegerField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='from_time',
            field=models.IntegerField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='month',
            field=models.IntegerField(verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='to_time',
            field=models.IntegerField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='year',
            field=models.IntegerField(verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='day',
            field=models.IntegerField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='from_time',
            field=models.IntegerField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='month',
            field=models.IntegerField(verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='to_time',
            field=models.IntegerField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='year',
            field=models.IntegerField(verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='day',
            field=models.IntegerField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='from_time',
            field=models.IntegerField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='month',
            field=models.IntegerField(verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='to_time',
            field=models.IntegerField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='year',
            field=models.IntegerField(verbose_name='年'),
        ),
    ]
