# Generated by Django 3.0.1 on 2020-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toei', '0020_auto_20200104_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcourt',
            name='use_flg',
            field=models.CharField(default=0, max_length=1, verbose_name='使用フラグ'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='court',
            field=models.CharField(choices=[('0', '府中の森公園'), ('1', '小金井公園'), ('2', '野川公園'), ('3', '井の頭恩賜公園'), ('4', '武蔵野中央公園'), ('5', '東大和南公園')], default=1, max_length=1, verbose_name='コート'),
        ),
        migrations.AlterField(
            model_name='getcourt',
            name='court',
            field=models.CharField(choices=[('0', '府中の森公園'), ('1', '小金井公園'), ('2', '野川公園'), ('3', '井の頭恩賜公園'), ('4', '武蔵野中央公園'), ('5', '東大和南公園')], default=1, max_length=1, verbose_name='コート'),
        ),
        migrations.AlterField(
            model_name='oddscourt',
            name='court',
            field=models.CharField(choices=[('0', '府中の森公園'), ('1', '小金井公園'), ('2', '野川公園'), ('3', '井の頭恩賜公園'), ('4', '武蔵野中央公園'), ('5', '東大和南公園')], default=1, max_length=1, verbose_name='コート'),
        ),
    ]
